POST http://localhost:8080/blog-1.0-SNAPSHOT/payments
Accept: application/json
Content-Type: application/json

{
  "value": "1000 PLN",
  "properties": {
    "cardNumber": "123456",
    "cvv": 255
  }
}

###

GET http://localhost:8080/blog-1.0-SNAPSHOT/payments/705f0160-9ba1-494b-98df-5f37da82948e
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/blog-1.0-SNAPSHOT/exchange-rate?money=100%20PLN
Accept: application/json

###

POST http://localhost:8080/blog-1.0-SNAPSHOT/messages
Accept: application/json
Content-Type: text/plain

Hello JMS

###

GET http://localhost:8080/blog-1.0-SNAPSHOT/mails
Accept: application/json

###

GET http://localhost:8080/blog-1.0-SNAPSHOT/kafka-messages
Accept: application/json

###