spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/blog
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    tls: true
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

sender: blog@training.pl
availableLanguages: pl
defaultLanguage: pl